---
kind: pipeline
type: docker
name: deploy-html-css-s3

steps:
  # ------------------------------
  # 1️⃣ Déploiement vers S3
  # ------------------------------
  - name: deploy-to-s3
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      bucket: buket-restaurant
      region: us-east-1
      source: ./
      target: /
      acl: public-read
      cache_control: max-age=31536000
      strip_components: 0 

# ------------------------------
# Déclencheurs
# ------------------------------
trigger:
  branch:
    - master
  event:
    - push
