hugo_env: &hugo_env
  BASE_URL: http://buket-restaurant.s3-website-us-east-1.amazonaws.com
  
kind: pipeline
type: docker
name: deploy-hugo-s3

steps:
  # ------------------------------
  # 1️⃣ Build Hugo
  # ------------------------------
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  # ------------------------------
  # 2️⃣ Déploiement vers S3 avec AWS CLI
  # ------------------------------
  - name: upload-to-s3
    image: amazon/aws-cli:2.13.7
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://buket-restaurant --delete

# ------------------------------
# Déclencheurs
# ------------------------------
trigger:
  branch:
    - master
  event:
    - push
    - custom
