# ============================================
# 🏗️ PIPELINE BUILD (toutes les branches)
# ============================================
kind: pipeline
type: docker
name: hugo-build

steps:
  - name: build-hugo
    image: peaceiris/hugo:v0.65.3-mod
    commands:
      - hugo --baseURL localhost/

# Trigger sur TOUTES les branches
trigger:
  event:
    - push
  branch:
    exclude:
      - master

---

# ------------------------------
# Pipeline de build + packager
# ------------------------------
kind: pipeline
type: docker
name: hugo-build-and-upload

steps:
  # Build Hugo
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      BASE_URL_PROD: http://buket-restaurant-staging.s3-website-us-east-1.amazonaws.com/
    commands:
      - hugo --baseURL $BASE_URL_PROD

  # Packager en tar.gz
  - name: package-build
    image: alpine:latest
    commands:
      - tar -czf build-${DRONE_COMMIT_SHA}.tar.gz -C public .

  # Upload compressé vers S3 (archive de build)
  - name: upload-to-s3
    image: amazon/aws-cli:2.13.7
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - export SHORT_SHA=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - aws s3 cp build-${DRONE_COMMIT_SHA}.tar.gz s3://buket-restaurant-release/release/resto-$SHORT_SHA.tar.gz

trigger:
  branch:
    - master
  event:
    - push


# ---

# ============================================
# 🏷️ BUILD + UPLOAD (tag)
# ============================================
# kind: pipeline
# type: docker
# name: hugo-build-and-upload-tag

# steps:
#   # Build Hugo
#   - name: hugo-build
#     image: peaceiris/hugo:v0.65.3-mod
#     environment:
#       BASE_URL_PROD: http://buket-restaurant-production.s3-website-us-east-1.amazonaws.com/
#     commands:
#       - hugo --baseURL $BASE_URL_PROD

# trigger:
#   event:
#     - tag
