hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/
  
kind: pipeline
type: docker
name: deploy-hugo-s3

steps:
  # ------------------------------
  # 1️⃣ Build Hugo
  # ------------------------------
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  # ------------------------------
  # 2️⃣ Déploiement vers S3
  # ------------------------------
  - name: upload
    image: plugins/s3
    settings:
      bucket: buket-restaurant
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token
      region: us-east-1
      source: public/**/*
      target: /
      acl: public-read
      cache_control: max-age=31536000
      strip_components: 0

# ------------------------------
# Déclencheurs
# ------------------------------
trigger:
  branch:
    - master
  event:
    - push
    - custom
